---
title: "Midterm Details"
author: "Stat 331"
output: rmdformats::readthedown
---

## Policies


  * You may use: any item on Canvas (including notes and solutions), any notes you have brought with you, and any resources online.  
  * You may NOT contact anyone, inside or outside this classroom, during the course of the exam.  This includes email, chat/messenger services, and posting on online forums and message boards. This also includes shared Google Docs; you should copy shared notes to a private file.
  * You may NOT use exam materials from previous years.
  * Violations of academic honesty include accessing and using any illegal materials, and giving or receiving help on this exam including looking at other student's exams, allowing other students to look at your own exam, and/or revealing any information about this exam or future exams to someone who has not yet taken it.
  *  Students who exhibit academic misconduct will be reported to the Office of Student Rights
and Responsibilities; academic dishonesty may be punishable by a grade of F in this course.
  * You may **not** discuss the exam with any other students until after the exams have been taken by all sections.
  * If you witness others exhibiting academic misconduct, you have a duty to report them to your
professor.

## Basic Instructions

 *  Please read all instructions carefully, especially regarding which files to upload to Canvas.
 
 *  Please use the templates provided to you.
 
 *  Late exams will have their grades deducted.  **Exams more than 5 minutes late will not be accepted.**
 
 *  You are free to use any approach - tidyverse, base R, other packages, or combinations thereof - to address the questions.

## The Data

Your dataset for the exam can be found on Canvas.  I suggest reading through the documentation in the Kaggle link and downloading the dataset in advance of the exam.

If you are not familiar with the Academy Awards, please don't hesistate to ask me or your classmates questions about the information in the dataset. 

However, any *coding work* you do in advance of the midterm may **not be shared** with your clasmates.


## Part One: Function Writing, sampling, and beautiful code (150 pts)

You will have the first 50 minutes of the exam to complete this section.

You will be asked to write a function to perform a task related to sampling from probability distributions.

This will be a relatively small and limited task - this part of the exam will **not** be under time pressure.


Of course, the most important thing is that you successfully and correctly accomplish the sampling task. However, I will also be grading on this being perfect, beautiful code.  You should be sure to:

* Name your variables and functions reasonably and informatively.

* Follow style guides, especially with regard to white space, parentheses, and brackets.

* Be deliberate about your objects and object types, and how you choose to store information.

* Write efficient code: do not duplicate analyses unnecessarily, use loops/map/apply when it is not needed, or create new objects you don't need.

* Write well-designed code: your main function should rely on helpful smaller functions, and all functions should take reasonable inputs and give reasonable outputs.

* Your code should have at least a few comments, explaining what your functions do.



## Part Two: Data Analysis (150 points)

In the final two hours of the exam, you will be asked to perform several data analysis tasks.

These tasks will focus on Unit 3 material; however, you will need knowledge from all 3 units of the class to fully complete your analyses.

You will turn in your `.html` and `.Rmd` files; only your `.html` file will be graded.  Make sure your `.html` output:

* Contains all your answers

* Shows your source code

* Does not contain extraneous output

* Uses good code style and design.


This section will be comparable in length and difficulty to Part Three of the midterm.
